# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build and deploy UI

on:
  push:
    branches: [ "master" ]


jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    
    - uses: actions/checkout@v3
        
    - name: Install dependencies
      run: npm install


    - name: build
      run: |
        $env:NODE_OPTIONS = "--openssl-legacy-provider"
        cd C:\frontend\actions-runner\_work\Embible-UI\Embible-UI
        ng build
        Remove-item -Recurse C:\frontend\nginx-1.24.0\nginx-1.24.0\html\*
        Copy-Item -Path C:\deploy\_work\Embible-UI\Embible-UI\dist\UI\* -Destination C:\frontend\nginx-1.24.0\nginx-1.24.0\html -Recurse -Force

