name: my workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [16.14]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: install and build
      run: npm install && ng build


